development:
  enabled: false
production:
  enabled: true
  suppress_app_log: true
  controller_enabled: true
  record_enabled: false
  job_enabled: true
  view_enabled: false
  mailer_enabled: true
test:
  enabled: false
